### PR TITLE
Inform about the ability to use pip

### PR DESCRIPTION
**Pull request by Singustromo**
Also changed the package name so pip does not install it as **launcher**

### CODE REVIEW

**Comment by Mord3rca** [comment]
Ok for the package name change, however, pip installation is redundant with venv installation, maybe you can only change the subtitle **Using venv** in **Using pip** ?

**Comment by Singustromo** [comment]
So you mean effectively removing the venv part all together? You may make the respective changes.

**Comment by Mord3rca** [comment]
Not removing, just changing the section name (since a venv install is a pip install)

**Comment by Singustromo** [comment]
You are totally right. I kind of forgot that you do the same according to the instructions but in a virtual environment.

**Comment by Mord3rca** [comment]
Fine with changes, can you do 2 commits ?
- 1 for the name change
- 1 for the update on README

**Comment by Singustromo** [comment]
How do I do that in GitHub? I only used plain git in the past and most of the time I just submitted patches.

**Comment by Mord3rca** [comment]
The easiest way in your case, is to reset your branch on master

Adding README.md and commiting
Adding `setup.py` and commiting

Then force push your branch

**Pull request closed without merging**
