### PR TITLE
Added info about AUR package for Arch Linux and Arch based systems

### PR DESCRIPTION
**Pull request by Regeneric**
I created a simple PKGBUILD for Arch for tagged releases. It doesn't use venv and pip for packages, but AUR.

### CODE REVIEW

**Comment by Mord3rca** [comment]
Hey !
I'm not on Arch, can someone else test this ?

**Comment by kshshton** [comment]
Works on my system

**Comment by Dragroth** [comment]
I've just checked on my machine and I confirm it's working.

**Comment by seeyd7** [comment]
Works for me

**Pull request merged**
